import { describe, expect, it, vi } from 'vitest';

import {
  graphSize,
  graphToPdf,
  isLayoutEngine,
  layoutEngines,
  loadGraphviz,
  MAX_GRAPHVIZ_CHARS,
  GraphvizSyntaxError,
  renderGraphviz,
  renderGraphvizText,
  stripPrologue,
  textFormats,
  type GraphvizEngine,
  type GraphvizResult,
  type PdfWriter,
} from './graphviz-render';
import { graphvizSamples } from './graphviz-samples';
import type { RasterDeps } from './mermaid-render';

const graphvizSvg = `<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN"
 "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<!-- Generated by graphviz -->
<svg width="62pt" height="116pt"
 viewBox="0.00 0.00 62.00 116.00" xmlns="http://www.w3.org/2000/svg"><g/></svg>
`;

function fakeEngine(result: GraphvizResult | (() => GraphvizResult)): GraphvizEngine {
  return {
    graphvizVersion: 'test',
    render: vi.fn(() => (typeof result === 'function' ? result() : result)),
  };
}

const rasterDeps: RasterDeps = {
  loadImage: vi.fn(async () => ({}) as CanvasImageSource),
  createCanvas: vi.fn(
    (width: number, height: number) =>
      ({
        width,
        height,
        getContext: () => ({ fillRect: vi.fn(), drawImage: vi.fn(), fillStyle: '' }),
        toBlob: (done: (blob: Blob) => void) => done(new Blob(['png'], { type: 'image/png' })),
      }) as unknown as HTMLCanvasElement,
  ),
};

describe('graphviz svg helpers', () => {
  it('reads the size in pixels from the point-based viewBox', () => {
    expect(graphSize(graphvizSvg)).toEqual({ width: 83, height: 155 });
    expect(graphSize('<svg viewBox="0 0 0 0"/>')).toEqual({ width: 1, height: 1 });
    expect(graphSize('<svg/>')).toEqual({ width: 800, height: 600 });
  });

  it('drops the prologue so the SVG can be re-wrapped', () => {
    expect(stripPrologue(graphvizSvg).startsWith('<svg width="62pt"')).toBe(true);
    expect(stripPrologue('<svg/>')).toBe('<svg/>');
  });

  it('lists every Graphviz layout engine and validates names', () => {
    expect(layoutEngines.map((engine) => engine.id)).toEqual(
      expect.arrayContaining(['dot', 'neato', 'fdp', 'sfdp', 'circo', 'twopi', 'osage', 'patchwork', 'nop', 'nop2']),
    );
    expect(isLayoutEngine('twopi')).toBe(true);
    expect(isLayoutEngine('bogus')).toBe(false);
  });
});

describe('renderGraphviz', () => {
  it('renders SVG through the engine, sizes it, and keeps warnings', async () => {
    const engine = fakeEngine({
      status: 'success',
      output: graphvizSvg,
      errors: [
        { level: 'warning', message: 'using box for unknown shape bogus\n' },
        { level: 'error', message: 'remove_overlap: Graphviz not built with triangulation library' },
        { message: '   ' },
      ],
    });
    const graph = await renderGraphviz('digraph { a -> b }', 'neato', engine);
    expect(engine.render).toHaveBeenCalledWith('digraph { a -> b }', { format: 'svg', engine: 'neato' });
    expect(graph.width).toBe(83);
    expect(graph.height).toBe(155);
    expect(graph.svg.startsWith('<svg')).toBe(true);
    expect(graph.svg).toContain('width="83" height="155"');
    expect(graph.warnings).toEqual([
      'using box for unknown shape bogus',
      'remove_overlap: Graphviz not built with triangulation library',
    ]);
  });

  it('rejects empty and oversized input before loading the engine', async () => {
    const engine = fakeEngine({ status: 'success', output: graphvizSvg, errors: [] });
    await expect(renderGraphviz('   ', 'dot', engine)).rejects.toThrow(/write some dot/i);
    await expect(renderGraphviz('x'.repeat(MAX_GRAPHVIZ_CHARS + 1), 'dot', engine)).rejects.toThrow(/limited to/i);
    expect(engine.render).not.toHaveBeenCalled();
  });

  it('turns parse failures into a GraphvizSyntaxError with only the error lines', async () => {
    const engine = fakeEngine({
      status: 'failure',
      errors: [
        { level: 'error', message: "syntax error in line 1 near '}'\n" },
        { level: 'warning', message: 'ignored' },
      ],
    });
    await expect(renderGraphviz('digraph { a -> }', 'dot', engine)).rejects.toThrow(GraphvizSyntaxError);
    await expect(renderGraphviz('digraph { a -> }', 'dot', engine)).rejects.toThrow("syntax error in line 1 near '}'");
    const silent = fakeEngine({ status: 'failure', errors: [] });
    await expect(renderGraphviz('x', 'dot', silent)).rejects.toThrow('Graphviz could not parse this graph.');
  });

  it('reports engine crashes with a way forward', async () => {
    const crashing = fakeEngine(() => {
      throw new Error('memory access out of bounds');
    });
    await expect(renderGraphviz('graph { a -- b }', 'sfdp', crashing)).rejects.toThrow(
      /stopped while laying out this graph \(memory access out of bounds\).*levels=1/,
    );
    const bare = fakeEngine(() => {
      throw 'trap';
    });
    await expect(renderGraphviz('graph { a -- b }', 'sfdp', bare)).rejects.toThrow(/laying out this graph\. Try another/);
  });

  it('produces Graphviz text formats', async () => {
    const engine = fakeEngine({ status: 'success', output: 'digraph { a }', errors: [] });
    expect(await renderGraphvizText('digraph { a }', 'canon', 'circo', engine)).toBe('digraph { a }');
    expect(engine.render).toHaveBeenCalledWith('digraph { a }', { format: 'canon', engine: 'circo' });
    expect(new Set(textFormats.map((format) => format.id)).size).toBe(textFormats.length);
  });
});

describe('graphToPdf', () => {
  it('embeds a 2x raster on a page the size of the graph', async () => {
    const writer: PdfWriter = { addImage: vi.fn(), output: vi.fn(() => new ArrayBuffer(4)) };
    const createPdf = vi.fn(async () => writer);
    const pdf = await graphToPdf({ svg: '<svg/>', width: 40, height: 20 }, createPdf, rasterDeps);
    expect(pdf.type).toBe('application/pdf');
    expect(createPdf).toHaveBeenCalledWith(40, 20);
    expect(writer.addImage).toHaveBeenCalledWith(expect.any(Uint8Array), 'PNG', 0, 0, 40, 20);
    expect(rasterDeps.createCanvas).toHaveBeenLastCalledWith(80, 40);
  });

  it('writes a real PDF with jsPDF by default', async () => {
    const png = Uint8Array.from(
      atob('iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAYAAAAfFcSJAAAADUlEQVR42mP8z8BQDwAEhQGAhKmMIQAAAABJRU5ErkJggg=='),
      (char) => char.charCodeAt(0),
    );
    const deps: RasterDeps = {
      ...rasterDeps,
      createCanvas: (width, height) =>
        ({
          width,
          height,
          getContext: () => ({ fillRect: vi.fn(), drawImage: vi.fn() }),
          toBlob: (done: (blob: Blob) => void) => done(new Blob([png], { type: 'image/png' })),
        }) as unknown as HTMLCanvasElement,
    };
    for (const [width, height] of [
      [30, 10],
      [10, 30],
    ]) {
      const pdf = await graphToPdf({ svg: '<svg/>', width, height }, undefined, deps);
      expect(new TextDecoder().decode(await pdf.slice(0, 5).arrayBuffer())).toBe('%PDF-');
    }
  });
});

describe('real Graphviz engine', () => {
  it('lays out every sample with its engine and writes every text format', async () => {
    const viz = await loadGraphviz();
    expect(await loadGraphviz()).toBe(viz);
    for (const sample of graphvizSamples) {
      const graph = await renderGraphviz(sample.code, sample.engine, viz);
      expect(graph.svg, sample.id).toMatch(/^<svg[\s\S]*<\/svg>\s*$/);
      expect(graph.width, sample.id).toBeGreaterThan(20);
    }
    for (const format of textFormats) {
      expect(await renderGraphvizText('digraph { a -> b }', format.id, 'dot', viz), format.id).not.toBe('');
    }
    await expect(renderGraphviz('digraph { a -> }', 'dot', viz)).rejects.toThrow(/syntax error in line 1/);
    // The default path loads the same shared instance.
    expect((await renderGraphviz('graph { layout=circo; a -- b -- c -- a }')).svg).toContain('<svg');

    // A trapped instance is discarded, so the next render gets a fresh one.
    const crashing = fakeEngine(() => {
      throw new Error('unreachable');
    });
    await expect(renderGraphviz('graph { a }', 'sfdp', crashing)).rejects.toThrow(GraphvizSyntaxError);
    expect(await loadGraphviz()).not.toBe(viz);
  }, 30_000);
});
